### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by ebonygrrl** [ebonygrrl/10-team-profile-generator#14]
Received undefined 
    at Object.writeFile (node:fs:2168:5)
    at writeToFile (C:\Users\abook\Desktop\bootcamp\10-team-profile-generator\index.js:155:8)
    at C:\Users\abook\Desktop\bootcamp\10-team-profile-generator\index.js:223:17

Tried to use JSON.stringify on output array.
Seems the error is solely on receiving data from templateBuilder.js

**Comment by ebonygrrl** [comment]
fs was expecting a single string expression
